### ISSUE TITLE
服务器繁忙 请稍后再试 (500)

### ISSUE THREAD

**Issue by MoYingJi** [HelloGrasscutter/Leekcutter#1]
我在 Grasscutter 正常运行
但是我想要运行 Leekcutter 时
启动看上去很正常（前面不正常的是我折腾出来的）
我想要登录时却显示服务器繁忙请稍后再试
客户端用的是SG用官服转换过来的国际服是可以正常进入我以前的
我尝试过重新clone和清空db文件夹都没用

控制台输出：（只按了一个进入游戏按钮）
```
D:\Genshin\Leekcutter>cd bat

D:\Genshin\Leekcutter\bat>call start

D:\Genshin\Leekcutter\bat>cd ..

D:\Genshin\Leekcutter>java -jar leekcutter-1.2.0-dev.jar
[15:55:29] [INFO] 正在启动Leekcutter...
[15:55:30] [INFO] 加载了 1 个 FetterCharacterCardData
[15:55:30] [INFO] 加载了 300 个 AvatarTalentData
[15:55:30] [INFO] 加载了 1 个 AvatarSkillData
[15:55:30] [INFO] 加载了 1 个 FetterData
[15:55:30] [INFO] 加载了 1 个 AvatarSkillDepotData
[15:55:30] [INFO] 加载了 1 个 MonsterDescribeData
[15:55:30] [INFO] 加载了 1 个 AvatarCostumeData
[15:55:30] [INFO] 加载了 1 个 DungeonData
[15:55:30] [INFO] 加载了 1 个 AvatarFetterLevelData
[15:55:30] [INFO] 加载了 1 个 DailyDungeonData
[15:55:30] [INFO] 加载了 1 个 NpcData
[15:55:30] [INFO] 加载了 1 个 ReliquaryMainPropData
[15:55:30] [INFO] 加载了 200 个 MonsterCurveData
[15:55:30] [INFO] 加载了 1 个 SceneData
[15:55:30] [INFO] 加载了 1 个 AvatarLevelData
[15:55:30] [INFO] 加载了 1 个 RewardData
[15:55:31] [INFO] 加载了 1 个 ItemData
[15:55:31] [ERROR] 资源文件加载失败: [AvatarPromoteExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.AvatarPromoteData.getAddProps()" is null
        at emu.grasscutter.data.def.AvatarPromoteData.onLoad(AvatarPromoteData.java:56)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [INFO] 加载了 1 个 ReliquaryAffixData
[15:55:31] [INFO] 加载了 1 个 WeaponLevelData
[15:55:31] [INFO] 加载了 1 个 ShopGoodsData
[15:55:31] [ERROR] 资源文件加载失败: [WeaponPromoteExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.WeaponPromoteData.getAddProps()" is null
        at emu.grasscutter.data.def.WeaponPromoteData.onLoad(WeaponPromoteData.java:56)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [INFO] 加载了 1 个 AvatarFlycloakData
[15:55:31] [INFO] 加载了 1 个 GadgetData
[15:55:31] [ERROR] 资源文件加载失败: [AvatarCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:124)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 10 common frames omitted
[15:55:31] [INFO] 加载了 1 个 ReliquarySetData
[15:55:31] [ERROR] 资源文件加载失败: [WeaponCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:124)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 10 common frames omitted
[15:55:31] [ERROR] 资源文件加载失败: [EquipAffixExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.def.EquipAffixData.getAddProps()" is null
        at emu.grasscutter.data.def.EquipAffixData.onLoad(EquipAffixData.java:50)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [INFO] 加载了 1 个 WorldLevelData
[15:55:31] [INFO] 加载了 1 个 PlayerLevelData
[15:55:31] [ERROR] 资源文件加载失败: [ReliquaryLevelExcelConfigData.json]
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.AddProps" is null
        at emu.grasscutter.data.def.ReliquaryLevelData.onLoad(ReliquaryLevelData.java:50)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [ERROR] 资源文件加载失败: [ProudSkillExcelConfigData.json]
java.lang.NullPointerException: Cannot invoke "String.length()" because the return value of "emu.grasscutter.data.def.ProudSkillData.getOpenConfig()" is null
        at emu.grasscutter.data.def.ProudSkillData.onLoad(ProudSkillData.java:88)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [ERROR] 资源文件加载失败: [MonsterExcelConfigData.json]
java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
        at emu.grasscutter.data.def.MonsterData.onLoad(MonsterData.java:173)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [ERROR] 资源文件加载失败: [AvatarExcelConfigData.json]
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "emu.grasscutter.data.def.RewardData.getRewardItemList()" is null
        at emu.grasscutter.data.def.AvatarData.onLoad(AvatarData.java:224)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:128)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:106)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [ERROR] 文物属性缺少权重！请检查ExcelBinOutput文件夹中的ReliquaryMapinPropertyXcelConfigData或ReliquaryAffixExcelConfigData文件。
[15:55:31] [ERROR] Error loading abilities
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarSkillDepotData.setAbilities(emu.grasscutter.data.custom.AbilityEmbryoEntry)" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:59)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
[15:55:31] [INFO] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[15:55:31] [INFO] Opened connection [connectionId{localValue:2, serverValue:13}] to localhost:27017
[15:55:31] [INFO] Opened connection [connectionId{localValue:1, serverValue:14}] to localhost:27017
[15:55:31] [INFO] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=21629000}
[15:55:32] [INFO] Opened connection [connectionId{localValue:3, serverValue:15}] to localhost:27017
[15:55:32] [INFO] Registered 109 PacketHandlers
[15:55:32] [INFO] Banners successfully loaded.
[15:55:32] [INFO] 商城数据载入完毕
[15:55:32] [ERROR] Unable to load shop data.
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "emu.grasscutter.data.def.ShopGoodsData.getCostItems()" is null
        at emu.grasscutter.game.shop.ShopInfo.<init>(ShopInfo.java:57)
        at emu.grasscutter.game.shop.ShopManager.lambda$loadShop$0(ShopManager.java:98)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at emu.grasscutter.game.shop.ShopManager.loadShop(ShopManager.java:94)
        at emu.grasscutter.game.shop.ShopManager.load(ShopManager.java:139)
        at emu.grasscutter.game.shop.ShopManager.<init>(ShopManager.java:49)
        at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:60)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:96)
[15:55:32] [INFO] 商城chest数据载入完毕
[15:55:32] [INFO] ShopChestBatchUse data 载入完毕
[15:55:32] [INFO] Using default implementation for ThreadExecutor
[15:55:32] [INFO] Job execution threads will use class loader of thread: main
[15:55:32] [INFO] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[15:55:32] [INFO] Quartz Scheduler v.2.3.2 created.
[15:55:32] [INFO] RAMJobStore initialized.
[15:55:32] [INFO] Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[15:55:32] [INFO] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[15:55:32] [INFO] Quartz scheduler version: 2.3.2
[15:55:32] [INFO] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[15:55:32] [INFO] 掉落物数据载入成功
[15:55:32] [INFO] Logging initialized @4099ms to org.eclipse.jetty.util.log.Slf4jLog
[15:55:32] [INFO] jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 17.0.3+7
[15:55:32] [INFO] x509=X509@384472bf(keystore_entry,h=[mydomain.com, localhost],w=[]) for Server@656ec00d[provider=null,keyStore=file:///D:/Genshin/Leekcutter/keystore.p12,trustStore=null]
[15:55:32] [INFO] Started ServerConnector@7c9beb51{SSL, (ssl, http/1.1)}{0.0.0.0:443}
[15:55:32] [INFO] Started @4635ms
[15:55:32] [INFO] Server listening on http://localhost:443
[15:55:32] [INFO] [Dispatch] Dispatch服务器已在端口 443 上开启
[15:55:32] [INFO] 完毕！! 如需要帮助, 请输入 "help" 并回车
[15:55:33] [INFO] Grasscutter is FREE software. If you have paid for this, you may have been scammed. Homepage: https://github.com/Grasscutters/Grasscutter
[15:55:33] [INFO] 游戏服务器已开启在端口 22102 上
[15:55:36] [WARN] Uncaught exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at emu.grasscutter.server.dispatch.DispatchServer.lambda$start$10(DispatchServer.java:309)
        at express.Express.lambda$post$4(Express.java:131)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:833)
[15:55:36] [WARN] Uncaught exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at emu.grasscutter.server.dispatch.DispatchServer.lambda$start$10(DispatchServer.java:309)
        at express.Express.lambda$post$4(Express.java:131)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:833)
[15:55:36] [WARN] Uncaught exception
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at emu.grasscutter.server.dispatch.DispatchServer.lambda$start$10(DispatchServer.java:309)
        at express.Express.lambda$post$4(Express.java:131)
        at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
        at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:121)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
        at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
        at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:129)
        at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
        at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:81)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.javalin.websocket.JavalinWsServlet.service(JavalinWsServlet.kt:51)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at io.javalin.core.JavalinServer$start$wsAndHttpHandler$1.doHandle(JavalinServer.kt:49)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
        at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:833)
>
```

屏幕截图：![OY}95I[_@XXXMYEI[D]K)`2.png](https://user-images.githubusercontent.com/64307394/166643461-1baa560d-331d-4a24-8728-60513658f928.png)

**Comment by MoYingJi** [comment]
Grasscutter用的jre8u202
Leekcutter用的jdk17.0.3.7
（17版本的实在找不到jre版本）

**Comment by MoYingJi** [comment]
请问如何解决 谢谢

**Comment by ccjjfdyqlhy** [comment]
我也有这个问题
